# Generated by Django 5.1.3 on 2024-11-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aluno_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFS',
            },
        ),
        migrations.AlterModelOptions(
            name='areadosaber',
            options={'verbose_name': 'Área do saber', 'verbose_name_plural': 'Áreas do saber'},
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
        migrations.AlterModelOptions(
            name='ocupacao',
            options={'verbose_name': 'Ocupação', 'verbose_name_plural': 'Ocupações'},
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uf', verbose_name='UF'),
        ),
    ]
