# Generated by Django 5.1.4 on 2025-01-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_avaliacao_aluno_disciplina_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(default=0, verbose_name='Idade'),
        ),
    ]
