# Generated by Django 5.1.4 on 2025-01-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pessoa_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
    ]
