# Generated by Django 5.1.4 on 2025-01-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_aluno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='endereco',
            field=models.CharField(default=1, max_length=100, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
