# Generated by Django 5.1.4 on 2025-01-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_instituicao_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='uf',
            name='abreviacao_uf',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
